# Generated by Django 4.2.4 on 2024-07-02 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subscribe', '0001_initial'),
        ('CompanyManagement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribeuser',
            name='user_dst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_user_dst_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscribeuser',
            name='user_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_user_src_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscribecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.company'),
        ),
        migrations.AddField(
            model_name='subscribecompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
