# Generated by Django 4.2.4 on 2024-06-25 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe',
            new_name='Subscribe_company',
        ),
        migrations.CreateModel(
            name='Subscribe_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_user_dst_set', to=settings.AUTH_USER_MODEL)),
                ('user_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_user_src_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
