# Generated by Django 4.2.4 on 2024-06-27 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0004_merge_20240627_0914'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subscribe', '0002_rename_subscribe_subscribe_company_subscribe_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribe_company',
            new_name='SubscribeCompany',
        ),
        migrations.RenameModel(
            old_name='Subscribe_user',
            new_name='SubscribeUser',
        ),
    ]
