# Generated by Django 4.2.4 on 2024-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='skill_required',
        ),
        migrations.AddField(
            model_name='position',
            name='position_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
