# Generated by Django 4.2.4 on 2024-07-02 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
        ('PositionManagement', '0001_initial'),
        ('CompanyManagement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='position_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.positiontag'),
        ),
        migrations.AddField(
            model_name='position',
            name='skill_required',
            field=models.ManyToManyField(blank=True, to='UserManagement.skill'),
        ),
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.company'),
        ),
        migrations.AddField(
            model_name='offer',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PositionManagement.position'),
        ),
        migrations.AddField(
            model_name='offer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PositionManagement.position'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
