# Generated by Django 4.2.4 on 2024-06-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
