# Generated by Django 4.2.4 on 2024-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_conversation_message'),
        ('PositionManagement', '0002_remove_position_skill_required_position_position_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='skill_required',
            field=models.ManyToManyField(blank=True, to='UserManagement.skill'),
        ),
    ]
