# Generated by Django 4.2.4 on 2024-06-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0002_position_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_tag',
        ),
    ]
