# Generated by Django 4.2.4 on 2024-06-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0003_remove_position_position_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PositionTag',
        ),
    ]
