# Generated by Django 4.2.4 on 2024-06-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0016_user_desired_position'),
        ('PositionManagement', '0004_delete_positiontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.positiontag'),
        ),
    ]
