# Generated by Django 4.2.4 on 2024-06-30 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CompanyManagement', '0008_remove_position_company_delete_application_and_more'),
        ('PositionManagement', '0005_position_position_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offer_at', models.DateTimeField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PositionManagement.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PositionManagement.position')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
