# Generated by Django 4.2.4 on 2024-06-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0006_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PositionManagement.application'),
        ),
    ]
