# Generated by Django 4.2.4 on 2024-07-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0009_alter_offer_is_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='application',
        ),
    ]
