# Generated by Django 4.2.4 on 2024-07-02 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.CharField(max_length=255)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='resources/company_images/')),
                ('company_subscription', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Companys',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Creator', 'Creator'), ('Admin', 'Admin'), ('Staff', 'Staff')], default='Staff', max_length=255)),
            ],
            options={
                'db_table': 'CompanyMembers',
            },
        ),
        migrations.CreateModel(
            name='JoinVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyManagement.company')),
            ],
        ),
    ]
