# Generated by Django 4.2.4 on 2024-06-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(auto_created=True, max_length=40, primary_key=True, serialize=False),
        ),
    ]
