# Generated by Django 4.2.4 on 2024-06-26 01:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0002_alter_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
