# Generated by Django 4.2.4 on 2024-06-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0003_alter_company_company_id'),
        ('CompanyManagement', '0003_company_company_subscription_and_more'),
    ]

    operations = [
    ]
