# Generated by Django 4.2.4 on 2024-06-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0004_merge_20240627_0907'),
        ('CompanyManagement', '0004_merge_20240627_0914'),
    ]

    operations = [
    ]
