# Generated by Django 4.2.4 on 2024-06-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyManagement', '0007_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='company',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
