# Generated by Django 4.2.4 on 2024-06-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_subscription',
            field=models.IntegerField(default=0),
        ),
    ]
