# Generated by Django 4.2.4 on 2024-06-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_user_blog_link_user_desired_position_user_education_and_more'),
        ('UserManagement', '0002_user_user_subscription'),
    ]

    operations = [
    ]
