# Generated by Django 4.2.4 on 2024-06-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='resources/avatars/'),
        ),
    ]
