# Generated by Django 4.2.4 on 2024-06-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0002_position_hr'),
        ('UserManagement', '0009_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cur_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='years_of_service',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='desired_position',
        ),
        migrations.AddField(
            model_name='user',
            name='desired_position',
            field=models.ManyToManyField(blank=True, null=True, to='PositionManagement.positiontag'),
        ),
    ]
