# Generated by Django 4.2.4 on 2024-06-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0003_remove_position_position_tag'),
        ('UserManagement', '0012_remove_user_desired_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desired_position',
            field=models.ManyToManyField(blank=True, to='PositionManagement.positiontag'),
        ),
    ]
