# Generated by Django 4.2.4 on 2024-06-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0014_remove_user_desired_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PositionTags',
                'unique_together': {('category', 'specialization')},
            },
        ),
    ]
