# Generated by Django 4.2.4 on 2024-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0015_positiontag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desired_position',
            field=models.ManyToManyField(blank=True, to='UserManagement.positiontag'),
        ),
    ]
