# Generated by Django 4.2.4 on 2024-06-30 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PositionManagement', '0008_application_offer_alter_offer_application'),
        ('NotificationCenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='PositionManagement.position'),
        ),
    ]
